CREATE TABLE HUTTE (
  NOM_HUTTE VARCHAR(45) PRIMARY KEY,
  SURFACE REAL NOT NULL,
  ANNEE DECIMAL(4, 0) NULL,
  HAUTEUR REAL NULL
);

CREATE TABLE SPECIALITE (
  NOM_SPE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE HABITANT (
  NOM_HAB VARCHAR(15) PRIMARY KEY,
  NOM_HUTTE VARCHAR(45),
  NOM_SPE VARCHAR(50),
  DATE_NAIS DATE NOT NULL,
  SEXE CHAR(1) DEFAULT 'M',
  CONSTRAINT FK_HAB_HUTTE FOREIGN KEY (NOM_HUTTE) REFERENCES HUTTE(NOM_HUTTE),
  CONSTRAINT FK_HAB_SPECIALITE FOREIGN KEY (NOM_SPE) REFERENCES SPECIALITE(NOM_SPE)
);

CREATE TABLE POTION (
  NOM_POTION VARCHAR(15) PRIMARY KEY,
  EFFET VARCHAR(30) NOT NULL,
  DUREE INTEGER DEFAULT 2 CONSTRAINT C_DURRE CHECK (DUREE BETWEEN 0 AND 120),
  INTERVALLE DECIMAL(7, 3) DEFAULT 3
);

CREATE TABLE PRISE (
  DATE DATE,
  NOM_HAB VARCHAR(15),
  NOM_POTION VARCHAR(15),
  QTE INTEGER DEFAULT 1,
  CONSTRAINT PK_PRISE PRIMARY KEY (DATE, NOM_HAB, NOM_POTION),
  CONSTRAINT FK_PRISE_HAB FOREIGN KEY (NOM_HAB) REFERENCES HABITANT(NOM_HAB),
  CONSTRAINT FK_PRISE_POTION FOREIGN KEY (NOM_POTION) REFERENCES POTION(NOM_POTION)
);
